services:
  db:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    ports:
      - 8432:8000
    command:
      - start
      - --log=debug
      - --user=root
      - --pass=root
      - memory